### ISSUE TITLE
kubelet does not honor calico cni certificate configuration 

### ISSUE THREAD

**Issue by pizzarabe** [coreos/coreos-kubernetes#754]
I used the coreos k8s doc to setup my cluster (https://coreos.com/kubernetes/docs/latest/deploy-workers.html).

According to https://github.com/projectcalico/calico-cni/blob/master/configuration.md#etcd-location you can configure the tls configuration within the cni file.

I configured my cni file on the worker like that to connect to a HTTPS only etcd:

```
cat /etc/kubernetes/cni/net.d/10-calico.conf 
{
    "name": "calico",
    "type": "flannel",
    "delegate": {
        "type": "calico",
        "etcd_endpoints": "https://alien4.domain:2379",
        "etcd_ca_cert_file": "/etc/ssl/alien/alien-chain.cert.pem",
        "etcd_cert_file": "/etc/ssl/alien/alien4.key.pem",
        "etcd_key_file": "/etc/ssl/alien/alien4.key.pem",
        "log_level": "none",
        "log_level_stderr": "info",
        "hostname": "10.169.1.134",
        "policy": {
          "type": "k8s",
          "k8s_api_root": "https://10.169.1.131:443/api/v1/",
          "k8s_client_key": "/etc/ssl/alien/alien4.key.pem",
          "k8s_client_certificate": "/etc/ssl/alien/alien4.cert.pem"
        }
    }
}
```
Please note
```
        "etcd_ca_cert_file": "/etc/ssl/alien/alien-chain.cert.pem",
        "etcd_cert_file": "/etc/ssl/alien/alien4.key.pem",
        "etcd_key_file": "/etc/ssl/alien/alien4.key.pem",
```

k8s works like expected, but I can not start any pods.

```
core@alien1 /tmp $ ./kubectl run example --image=nginx
deployment "example" created

core@alien1 /tmp $ ./kubectl get deployment
NAME      DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
example   1         1         1            0           12s

core@alien1 /tmp $ ./kubectl get pods      
NAME                      READY     STATUS              RESTARTS   AGE
example-567974352-l6ctu   0/1       ContainerCreating   0          17s

./kubectl describe pod example-567974352-l6ctu
Name:		example-567974352-l6ctu
Namespace:	default
Node:		10.169.1.134/10.169.1.134
Start Time:	Tue, 08 Nov 2016 16:06:45 +0100
Labels:		pod-template-hash=567974352
		run=example
Status:		Pending
IP:		
Controllers:	ReplicaSet/example-567974352
Containers:
  example:
    Container ID:	
    Image:		nginx
    Image ID:		
    Port:		
    State:		Waiting
      Reason:		ContainerCreating
    Ready:		False
    Restart Count:	0
    Volume Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-ei3bf (ro)
    Environment Variables:	<none>
Conditions:
  Type		Status
  Initialized 	True 
  Ready 	False 
  PodScheduled 	True 
Volumes:
  default-token-ei3bf:
    Type:	Secret (a volume populated by a Secret)
    SecretName:	default-token-ei3bf
QoS Class:	BestEffort
Tolerations:	<none>
Events:
  FirstSeen	LastSeen	Count	From			SubobjectPath	Type		Reason		Message
  ---------	--------	-----	----			-------------	--------	------		-------
  36s		36s		1	{default-scheduler }			Normal		Scheduled	Successfully assigned example-567974352-l6ctu to 10.169.1.134
  35s		1s		34	{kubelet 10.169.1.134}			Warning		FailedSync	Error syncing pod, skipping: failed to "SetupNetwork" for "example-567974352-l6ctu_default" with SetupNetworkError: "Failed to setup network for pod \"example-567974352-l6ctu_default(f70e6530-a5c4-11e6-b460-005056b73cb0)\" using network plugins \"cni\": Unhandled Exception killed plugin; Skipping pod"
```

journalctl show the problem on the specific worker node, the certificate variables are not set.

```
journalctl -u kubelet
----
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]: DataStoreError: Invalid ETCD_CA_CERT_FILE. Certificate Authority cert is required and must be a readable file path. Value provided:
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]: 2016-11-08 15:22:04,380 22336 [default/example-567974352-l6ctu] ERROR CNI Error:
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]: {
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]:   "msg": "Unhandled Exception killed plugin",
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]:   "cniVersion": "0.1.0",
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]:   "code": 100,
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]:   "details": null
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]: }
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]: Traceback (most recent call last):
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]:   File "<string>", line 773, in main
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]:   File "<string>", line 64, in __init__
Nov 08 16:22:04 alien4 kubelet-wrapper[1588]:   File "site-packages/pycalico/datastore.py", line 229, in __init__

----

```
I can configure the variables through the rkt

```
  --set-env=ETCD_CA_CERT_FILE=/etc/ssl/alien/alien-chain.cert.pem
  --set-env=ETCD_CERT_FILE=/etc/ssl/alien/alien4.cert.pem
  --set-env=ETCD_KEY_FILE=/etc/ssl/alien/alien4.key.pem

```

systemd unit file used to start kubelet:

```
systemctl cat kubelet
# /etc/systemd/system/kubelet.service
[Service]
ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
ExecStartPre=/usr/bin/mkdir -p /var/log/containers
Environment=KUBELET_VERSION=v1.4.5_coreos.0
Environment="RKT_OPTS=--volume var-log,kind=host,source=/var/log \
  --mount volume=var-log,target=/var/log \
  --volume dns,kind=host,source=/etc/resolv.conf \
  --mount volume=dns,target=/etc/resolv.conf \
  --volume ssl-alien,kind=host,source=/etc/ssl/alien,readOnly=true \
  --mount volume=ssl-alien,target=/etc/ssl/alien \"
  ExecStart=/usr/lib/coreos/kubelet-wrapper \
  --api-servers=https://10.169.1.131 \
  --network-plugin-dir=/etc/kubernetes/cni/net.d \
  --network-plugin=cni \
  --register-node=true \
  --allow-privileged=true \
  --config=/etc/kubernetes/manifests \
  --hostname-override=10.169.1.134  \
  --cluster-dns=10.2.0.2 \
  --cluster-domain=cluster.local \
  --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
  --tls-cert-file=/etc/ssl/alien/alien4.rcert.pem \
  --tls-private-key-file=/etc/ssl/alien/alien4.key.pem
Restart=always
RestartSec=10
[Install]
WantedBy=multi-user.target
```

Is this a bug with the kubelet container...?

**Comment by george-angel** [comment]
I'm seeing exactly the same issue, here is my worker's userdata for reference:

```
#cloud-config
---
coreos:
  flannel:
    interface: $private_ipv4
    etcd_endpoints: ${etcd_address}
    etcd_cafile: /etc/kubernetes/ssl/ca.pem
    etcd_certfile: /etc/kubernetes/ssl/k8s-worker.pem
    etcd_keyfile: /etc/kubernetes/ssl/k8s-worker-key.pem
  units:
    - name: docker.service
      enable: true
      command: start
      drop-ins:
        - name: 20-cni.conf
          content: |
            [Service]
            EnvironmentFile=/etc/kubernetes/cni/docker_opts_cni.env

        - name: 40-flannel.conf
          content: |
            [Unit]
            Requires=flanneld.service
            After=flanneld.service

    - name: flanneld.service
      enable: true
      command: start
      drop-ins:
        - name: 10-etcd.conf
          content: |
            [Unit]
            Requires=get-ssl.service
            After=get-ssl.service
            [Service]
            Environment="ETCD_SSL_DIR=/etc/kubernetes/ssl"

    - name: rpc-statd.service
      command: start
      enable: true

    - name: kubelet.service
      enable: true
      command: start
      content: |
        [Unit]
        Requires=docker.service
        After=docker.service
        [Service]
        ExecStartPre=/usr/bin/mkdir -p /etc/kubernetes/manifests
        ExecStartPre=/usr/bin/mkdir -p /var/log/containers
        Environment=KUBELET_VERSION=${k8s_ver}
        Environment=KUBELET_ACI=${hyperkube_image_repo}
        Environment="RKT_OPTS=--volume var-log,kind=host,source=/var/log \
          --mount volume=var-log,target=/var/log \
          --volume cni-conf,kind=host,source=/etc/cni/net.d \
          --mount volume=cni-conf,target=/etc/cni/net.d \
          --volume tls,kind=host,source=/etc/kubernetes/ssl \
          --mount volume=tls,target=/etc/kubernetes/ssl \
          --volume dns,kind=host,source=/etc/resolv.conf \
          --mount volume=dns,target=/etc/resolv.conf"
        ExecStart=/usr/lib/coreos/kubelet-wrapper \
        --api-servers=https://${master_address} \
        --network-plugin-dir=/etc/cni/net.d \
        --network-plugin=${network_plugin} \
        --register-node=true \
        --allow-privileged=true \
        --pod-manifest-path=/etc/kubernetes/manifests \
        --hostname-override=$private_ipv4 \
        --cluster_dns=${dns_service_ip} \
        --cluster_domain=cluster.local \
        --cloud-provider=aws \
        --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml \
        --tls-cert-file=/etc/kubernetes/ssl/k8s-worker.pem \
        --tls-private-key-file=/etc/kubernetes/ssl/k8s-worker-key.pem
        Restart=always
        RestartSec=10
        [Install]
        WantedBy=multi-user.target

    - name: calico-node.service
      enable: true
      command: start
      content: |
        [Unit]
        Description=Calico per-host agent
        Requires=network-online.target
        After=network-online.target

        [Service]
        Slice=machine.slice
        Environment=CALICO_DISABLE_FILE_LOGGING=true
        Environment=HOSTNAME=$private_ipv4
        Environment=IP=$private_ipv4
        Environment=FELIX_FELIXHOSTNAME=$private_ipv4
        Environment=CALICO_NETWORKING=false
        Environment=NO_DEFAULT_POOLS=true
        Environment=ETCD_ENDPOINTS=${etcd_address}
        Environment=ETCD_CA_CERT_FILE=/calico-secrets/etcd-ca
        Environment=ETCD_KEY_FILE=/calico-secrets/etcd-key
        Environment=ETCD_CERT_FILE=/calico-secrets/etcd-cert
        ExecStart=/usr/bin/rkt run --inherit-env --stage1-from-dir=stage1-fly.aci \
        --volume=modules,kind=host,source=/lib/modules,readOnly=false \
        --mount=volume=modules,target=/lib/modules \
        --volume=dns,kind=host,source=/etc/resolv.conf,readOnly=true \
        --mount=volume=dns,target=/etc/resolv.conf \
        --volume=tls,kind=host,source=/etc/kubernetes/ssl,readOnly=true \
        --mount=volume=tls,target=/calico-secrets \
        --trust-keys-from-https quay.io/calico/node:v0.22.0

        KillMode=mixed
        Restart=always
        TimeoutStartSec=0

        [Install]
        WantedBy=multi-user.target

    - name: s3-iam-get.service
      command: start
      content: |
        [Unit]
        After=network-online.target
        Description=Install s3-iam-get
        Requires=network-online.target
        [Service]
        ExecStartPre=-/usr/bin/mkdir -p /opt/bin
        ExecStart=/usr/bin/curl -L -o /opt/bin/s3-iam-get \
          https://raw.githubusercontent.com/kz8s/s3-iam-get/master/s3-iam-get
        ExecStart=/usr/bin/chmod +x /opt/bin/s3-iam-get
        RemainAfterExit=yes
        Type=oneshot

    - name: get-ssl.service
      command: start
      content: |
        [Unit]
        Description=Get ssl artifacts from s3 bucket using IAM role
        Requires=s3-iam-get.service
        After=s3-iam-get.service
        [Service]
        ExecStartPre=-/usr/bin/mkdir -p /etc/kubernetes/ssl
        ExecStart=/bin/sh -c "/opt/bin/s3-iam-get ${ssl_tar} | tar xv -C /etc/kubernetes/ssl/"
        # Create symlink for keys to have a consistent location in the calico manifest to read them
        ExecStart=-/bin/sh -c "cd /etc/kubernetes/ssl/ && ln -s k8s-worker.pem etcd-cert && ln -s k8s-worker-key.pem etcd-key && ln -s ca.pem etcd-ca"
        RemainAfterExit=yes
        Type=oneshot

write_files:
  - path: /etc/kubernetes/cni/docker_opts_cni.env
    content: |
      DOCKER_OPT_BIP=""
      DOCKER_OPT_IPMASQ=""
      DOCKER_OPTS="--bridge=none"

  - path: /etc/kubernetes/manifests/kube-proxy.yaml
    content: |
        apiVersion: v1
        kind: Pod
        metadata:
          name: kube-proxy
          namespace: kube-system
        spec:
          hostNetwork: true
          containers:
          - name: kube-proxy
            image: ${hyperkube_image_repo}:${k8s_ver}
            command:
            - /hyperkube
            - proxy
            - --master=https://${master_address}
            - --kubeconfig=/etc/kubernetes/worker-kubeconfig.yaml
            - --proxy-mode=iptables
            securityContext:
              privileged: true
            volumeMounts:
              - mountPath: /etc/ssl/certs
                name: "ssl-certs"
              - mountPath: /etc/kubernetes/worker-kubeconfig.yaml
                name: "kubeconfig"
                readOnly: true
              - mountPath: /etc/kubernetes/ssl
                name: "etc-kube-ssl"
                readOnly: true
          volumes:
            - name: "ssl-certs"
              hostPath:
                path: "/usr/share/ca-certificates"
            - name: "kubeconfig"
              hostPath:
                path: "/etc/kubernetes/worker-kubeconfig.yaml"
            - name: "etc-kube-ssl"
              hostPath:
                path: "/etc/kubernetes/ssl"

  - path: /etc/kubernetes/worker-kubeconfig.yaml
    content: |
        apiVersion: v1
        kind: Config
        clusters:
        - name: local
          cluster:
            certificate-authority: /etc/kubernetes/ssl/ca.pem
        users:
        - name: kubelet
          user:
            client-certificate: /etc/kubernetes/ssl/k8s-worker.pem
            client-key: /etc/kubernetes/ssl/k8s-worker-key.pem
        contexts:
        - context:
            cluster: local
            user: kubelet
          name: kubelet-context
        current-context: kubelet-context

  - path: /etc/cni/net.d/10-calico.conf
    content: |
        {
            "name": "calico",
            "type": "flannel",
            "delegate": {
                "type": "calico",
                "etcd_endpoints": "${etcd_address}",
                "etcd_key_file": "/etc/kubernetes/ssl/etcd-key",
                "etcd_cert_file": "/etc/kubernetes/ssl/etcd-cert",
                "etcd_ca_cert_file": "/etc/kubernetes/ssl/etcd-ca",
                "log_level": "none",
                "log_level_stderr": "info",
                "hostname": "$private_ipv4",
                "policy": {
                    "type": "k8s",
                    "k8s_api_root": "https://${master_address}:443/api/v1/",
                    "k8s_client_key": "/etc/kubernetes/ssl/k8s-worker-key.pem",
                    "k8s_client_certificate": "/etc/kubernetes/ssl/k8s-worker.pem"
                }
            }
        }

  - path: /etc/prom-text-collectors/machine_role.prom
    content: |
      machine_role{role="worker"} 1
```

**Comment by robszumski** [comment]
@tomdee Can you take a look at this?

**Comment by matthewdupre** [comment]
(FYI Tom's on vacation until next week)

**Comment by caseydavenport** [comment]
@pizzarabe it looks like you're writing the file to `/etc/kubernetes/cni/net.d/10-calico.conf`, but your kubelet container doesn't mount that directory, so I don't think the kubelet is picking up the config file.

```
Environment="RKT_OPTS=--volume var-log,kind=host,source=/var/log \
  --mount volume=var-log,target=/var/log \
  --volume dns,kind=host,source=/etc/resolv.conf \
  --mount volume=dns,target=/etc/resolv.conf \
  --volume ssl-alien,kind=host,source=/etc/ssl/alien,readOnly=true \
  --mount volume=ssl-alien,target=/etc/ssl/alien \"
```

**Comment by pizzarabe** [comment]
@caseydavenport thank you for the information. I checked the kubelet-wrapper script and it is mounting the whole /etc/kubernetes folder. I guess this is enought.

```
exec /usr/bin/rkt run \
  --volume etc-kubernetes,kind=host,source=/etc/kubernetes \
  --volume etc-ssl-certs,kind=host,source=/usr/share/ca-certificates \
  --volume var-lib-docker,kind=host,source=/var/lib/docker \
  --volume var-lib-kubelet,kind=host,source=/var/lib/kubelet \
  --volume os-release,kind=host,source=/usr/lib/os-release \
  --volume run,kind=host,source=/run \
  --mount volume=etc-kubernetes,target=/etc/kubernetes \
  --mount volume=etc-ssl-certs,target=/etc/ssl/certs \
  --mount volume=var-lib-docker,target=/var/lib/docker \
  --mount volume=var-lib-kubelet,target=/var/lib/kubelet \
  --mount volume=os-release,target=/etc/os-release \
  --mount volume=run,target=/run \
  --trust-keys-from-https \
  $RKT_OPTS \
```

I can verify that the cni file is there:

```
alien2 net.d # pwd
/var/lib/rkt/pods/run/8d-.../stage1/rootfs/opt/stage2/hyperkube/rootfs/etc/kubernetes/cni/net.d
alien2 net.d # ls
10-calico.conf
```
but there is also a cni folder in the /etc/ folder of my pod
```
alien2 net.d # pwd
/var/lib/rkt/pods/run/8d-.../stage1/rootfs/opt/stage2/hyperkube/rootfs/etc/cni/net.d
alien2 net.d # ls
10-containernet.conf  99-loopback.conf
```

**Comment by caseydavenport** [comment]
@pizzarabe I think I understand what is going on.

The hyperkube image currently comes with a pretty old version of the Calico CNI binaries (v1.3.1), which don't support the `etcd_ca_cert_file` arguments (see https://github.com/projectcalico/calico-cni/blob/v1.3.1/configuration.md) so they are being ignored.

I'd recommend upgrading the binary to the latest release - v1.5.1

**Comment by pizzarabe** [comment]
Is there something else to do then update https://github.com/coreos/kubernetes/blob/coreos-hyperkube-v1.4.6/cluster/images/hyperkube/Makefile#L103 to 1.5.1 ?

**Comment by caseydavenport** [comment]
@pizzarabe that is likely the first step.

I think there have been some minor tweaks to the CNI config format that Calico expects in that timeframe, so there may be a corresponding change to the CNI config file.

**Comment by caseydavenport** [comment]
@pizzarabe I think the only different is that v1.5.1 will require the `k8s_certificate_authority` field in the CNI config, whereas v1.3.1 doesn't.

**Comment by pizzarabe** [comment]
@caseydavenport according to the docs the (deprecaded) "k8s-annotations" is also remove with > 1.5.0

>Previous versions of the plugin (v1.3.1 and earlier) supported an alternative type called k8s-annotations This uses annotations on pods to specify network policy but is no longer supported.
 http://docs.projectcalico.org/master/reference/cni-plugin/configuration

**Comment by caseydavenport** [comment]
Hm, yeah.  It is marked as deprecated..  Support hasn't been removed yet, but it looks like we should switch to a kubeconfig file for specifying API access configuration instead so we're future-proof.

CC @heschlie

**Comment by heschlie** [comment]
This was fixed when we moved to a self-hosted install in #768

**Comment by pizzarabe** [comment]
I will close this issue, I guess it is fixed.
